name: gfx-rs
highlighter: rouge
theme: jekyll-theme-midnight
title: gfx-rs nuts and bolts
description: gfx-rs is a project bringing efficient cross-platform graphics to rust. This blog supposedly hosts the major milestones, concepts, and recaps of the project.
github: https://www.github.com/gfx-rs
about: The gfx-rs blog
urls:
    - text: github
      url: https://github.com/gfx-rs/wgpu
plugins:
    - jekyll-feed
